# Site settings
title: Christina Everman
description: Software Developer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Christina Everman
user_description: I'm a software developer with a B.S. in Computer Science from Arizona State University and experience with full-stack web development. I also minored in Japanese and completed the game development certificate program at ASU. In my free time I enjoy learning new technologies, playing video games, and cooking Japanese food.
user_title: Software Developer
#email: anon@anon.com
#twitter_username: lorem_ipsum
github_username:  christinaeverman
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
